name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '42 5 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest] # TODO: fix code to run on Windows as well, windows-latest
        perl: [ '5.32', 5.36 ]
        exclude:
          - runner: windows-latest
            perl: '5.36'

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Perl ${{matrix.perl}}
    steps:
    - uses: actions/checkout@v2

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}
          #distribution: strawberry

    #- name: Install cpanm
    #  if: ${{ matrix.runner != "windows-latest" }}
    #  run: |
    #    curl -L https://cpanmin.us | perl - App::cpanminus

    - name: Install module
      run: |
         cpanm --installdeps --notest .

    - name: Run tests
      run: |
        perl Makefile.PL
        make
        make test
